.TH "huffar" "1" "0.1.1" "Dmitriy A. Perlow aka DAP-DarkneSS" ""
.SH "NAME"
A C99 Huffman archiver implementation.
.br
.SH "SYNTAX"
huffar <\fIfilename\fR1> [\fIoption\fR] <\fIfilename\fR2>
.br
.SH "OPTIONS"
<InputFile> \fB-c \fR<File.ha>
.br
		Compress <InputFile> into <File.ha>.
.br

<File.ha> \fB-x \fR<OutputFile>
.br
		Decompress <File.ha> into <OutputFile>.
.br

\fB--help\fR
.br
		Output help information and exit.
.br
.SH "AUTHORS"
Code: Dmitriy A. Perlow https://github.com/DAP-DarkneSS
.br

Idea: EPAM LLPD Linux Development Courses https://github.com/d4s/linux_courses/tree/master/epam
.br
